"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, AlertCircle, Info, Wrench, CheckCircle2 } from "lucide-react";
import { PageHeader } from "@/components/dashboard/PageHeader";
import { ChartCard } from "@/components/charts/ChartCard";
import { Card, Badge, Button } from "@/components/ui";
import { quality, meta } from "@/lib/dataset";
import { fmtInt, SEVERITY_COLORS, SEVERITY_TEXT } from "@/config";

const CODE_LABELS: Record<string, { label: string; why: string }> = {
  ATTENDANCE_MISMATCH: { label: "Present + Absent ≠ Registered", why: "The three headcount columns do not reconcile, so there is no single consistent enrolment model on these rows." },
  VERIFIED_EXCEEDS_REGISTERED: { label: "CNIC Verified exceeds Registered", why: "More trainees were CNIC-verified than were ever registered on the biometric device. One of the two counts is wrong." },
  OVER_CAPACITY: { label: "Registered exceeds Approved Capacity", why: "More trainees registered than the sanctioned seat count allows." },
  ZERO_REGISTERED: { label: "No trainees registered", why: "A trade was approved but nobody registered. Real signal, not corruption — kept in the dataset." },
  ZERO_CAPACITY: { label: "Approved Capacity is zero", why: "Every rate with capacity as denominator returns null on these rows rather than dividing by zero." },
  BATCH_MISSING: { label: "Batch not recorded", why: "Batch is blank, so these rows cannot be attributed to a cohort." },
  BATCH_ZERO: { label: "Batch recorded as 0", why: "Zero is not a valid batch number; treated as missing." },
  COMPONENT_OVER_MAX: { label: "Score exceeds its stated maximum", why: "A component scored above the ceiling printed in its own column header — most likely a value typed into the wrong column." },
  COMPONENT_MISSING: { label: "Score component missing", why: "Treated as 0 for the sum, and flagged rather than silently dropped." },
  NON_NUMERIC: { label: "Non-numeric value in a numeric column", why: "Text where a number was expected." },
  TRADE_NAME_VARIANTS: { label: "Trade spelled multiple ways", why: "The same Trade Code appears under several name spellings. Aggregation keys on the code; the most common spelling is displayed." },
  TOTAL_SCORE_MISMATCH: { label: "Stored Total Score disagrees with its own trade rows", why: "The workbook's Total Score column uses five different formulas and does not always equal the mean of the institute's trade scores. The dashboard recomputes it." },
  AMBIGUOUS_INSTITUTE: { label: "Institute ID carries more than one name", why: "Institute identity is ambiguous, which affects ranking and the institute profile." },
};

const ICONS = { high: AlertTriangle, medium: AlertCircle, low: Info };

export default function DataQualityPage() {
  const [severity, setSeverity] = useState<"all" | "high" | "medium" | "low">("all");
  const [code, setCode] = useState<string | null>(null);

  const shown = useMemo(() => quality.issues.filter((i) =>
    (severity === "all" || i.severity === severity) && (code === null || i.code === code)).slice(0, 400),
    [severity, code]);

  const codeRows = useMemo(() => Object.entries(quality.byCode)
    .map(([c, n]) => ({ code: c, n, severity: quality.issues.find((i) => i.code === c)!.severity }))
    .sort((a, b) => b.n - a.n), []);

  const completeness = quality.totals.completeness * 100;

  return (
    <>
      <PageHeader page="Data_Quality" title="Data Quality Center"
        description="Every defect found in the source workbook. Nothing is deleted or silently corrected — problems are reported so they can be fixed at source." />

      <div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-6">
        <Stat label="Total records" value={fmtInt(quality.totals.rows)} sub={`${quality.totals.institutes} institutes`} icon={CheckCircle2} color="#2563eb" />
        <Stat label="Completeness" value={completeness.toFixed(2) + "%"} sub={`${fmtInt(quality.totals.filledCells)} of ${fmtInt(quality.totals.cells)} cells`} icon={CheckCircle2} color={completeness > 95 ? "#10b981" : "#d97706"} />
        <Stat label="Repairs applied" value={String(quality.totals.repairs)} sub="logged below" icon={Wrench} color="#7c3aed" />
        <Stat label="High severity" value={String(quality.bySeverity.high ?? 0)} sub="distorts headline figures" icon={AlertTriangle} color="#dc2626" />
        <Stat label="Medium" value={String(quality.bySeverity.medium ?? 0)} sub="affects a module" icon={AlertCircle} color="#d97706" />
        <Stat label="Low" value={String(quality.bySeverity.low ?? 0)} sub="cosmetic" icon={Info} color="#64798f" />
      </div>

      <div className="mb-4 grid gap-3 lg:grid-cols-2">
        <ChartCard title="Issues by type" height={330}
          methodology={<>Every validation rule that fired during ingest, counted. Generated by <code>scripts/build-data.mjs</code> on each build.</>}
          data={codeRows.map((c) => ({ label: CODE_LABELS[c.code]?.label ?? c.code, value: c.n }))}
          option={{
            grid: { left: 8, right: 44, top: 8, bottom: 8, containLabel: true },
            tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
            xAxis: { type: "value" },
            yAxis: {
              type: "category",
              data: [...codeRows].reverse().map((c) => {
                const l = CODE_LABELS[c.code]?.label ?? c.code;
                return l.length > 32 ? l.slice(0, 31) + "…" : l;
              }),
              axisLabel: { fontSize: 9.5 },
            },
            series: [{
              type: "bar", barMaxWidth: 13,
              label: { show: true, position: "right", fontSize: 9.5 },
              data: [...codeRows].reverse().map((c) => ({
                value: c.n, itemStyle: { borderRadius: [0, 3, 3, 0], color: SEVERITY_COLORS[c.severity] },
              })),
            }],
          }} />

        <Card className="print-avoid overflow-hidden">
          <div className="border-b border-[var(--border)] px-4 py-3">
            <h3 className="text-[13px] font-semibold">Repairs applied at ingest</h3>
            <p className="mt-0.5 text-[11px] text-[var(--text-muted)]">
              These are the only value changes the pipeline makes. Every other defect is reported, not corrected.
            </p>
          </div>
          <table className="w-full text-xs">
            <thead className="bg-[var(--surface-2)]">
              <tr>{["Excel row", "Field", "In workbook", "Used", "Reason"].map((h) => (
                <th key={h} scope="col" className="border-b border-[var(--border)] px-3 py-2 text-left text-[10px] font-semibold uppercase tracking-wide text-[var(--text-muted)]">{h}</th>))}
              </tr>
            </thead>
            <tbody>
              {quality.repairs.map((r, i) => (
                <tr key={i} className="border-b border-[var(--border)] last:border-0">
                  <td className="num px-3 py-2">{r.row}</td>
                  <td className="px-3 py-2 font-medium">{r.field}</td>
                  <td className="px-3 py-2"><code className="rounded bg-red-50 px-1 py-0.5 text-red-700 dark:bg-red-950 dark:text-red-300">{r.from}</code></td>
                  <td className="num px-3 py-2"><code className="rounded bg-emerald-50 px-1 py-0.5 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">{r.to}</code></td>
                  <td className="px-3 py-2 text-[var(--text-muted)]">{r.reason}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Card>
      </div>

      <Card className="print-avoid overflow-hidden">
        <div className="flex flex-wrap items-center gap-2 border-b border-[var(--border)] px-4 py-3">
          <h3 className="text-[13px] font-semibold">Issue register</h3>
          <div className="no-print ml-auto flex flex-wrap items-center gap-1.5">
            {(["all", "high", "medium", "low"] as const).map((s) => (
              <button key={s} onClick={() => setSeverity(s)}
                className={`rounded-md px-2 py-1 text-[11px] font-medium capitalize ${severity === s ? "bg-brand-600 text-white" : "border border-[var(--border)] hover:bg-[var(--surface-3)]"}`}>
                {s}
              </button>
            ))}
            {code && <Button size="sm" variant="danger" onClick={() => setCode(null)}>Clear type</Button>}
          </div>
        </div>

        <div className="no-print flex flex-wrap gap-1.5 border-b border-[var(--border)] px-4 py-2">
          {codeRows.map((c) => (
            <button key={c.code} onClick={() => setCode(code === c.code ? null : c.code)}
              className={`rounded-full px-2 py-0.5 text-[10px] font-medium transition-opacity ${code === c.code ? "" : "opacity-55 hover:opacity-90"}`}
              style={{ background: SEVERITY_COLORS[c.severity] + "1f", color: SEVERITY_TEXT[c.severity] }}>
              {CODE_LABELS[c.code]?.label ?? c.code} · {c.n}
            </button>
          ))}
        </div>

        {code && CODE_LABELS[code] && (
          <p className="border-b border-[var(--border)] bg-[var(--surface-2)] px-4 py-2.5 text-[11px] leading-relaxed">
            <strong>Why this matters.</strong> {CODE_LABELS[code].why}
          </p>
        )}

        <div className="max-h-[520px] overflow-auto">
          <table className="w-full text-xs">
            <thead className="sticky top-0 bg-[var(--surface-2)]">
              <tr>{["Severity", "Issue", "Excel row", "Detail"].map((h) => (
                <th key={h} scope="col" className="border-b border-[var(--border)] px-3 py-2 text-left text-[10px] font-semibold uppercase tracking-wide text-[var(--text-muted)]">{h}</th>))}
              </tr>
            </thead>
            <tbody>
              {shown.map((iss, i) => {
                const Icon = ICONS[iss.severity];
                return (
                  <tr key={i} className="border-b border-[var(--border)] last:border-0">
                    <td className="px-3 py-1.5">
                      <span className="inline-flex items-center gap-1 text-[11px] font-medium capitalize" style={{ color: SEVERITY_TEXT[iss.severity] }}>
                        <Icon size={11} /> {iss.severity}
                      </span>
                    </td>
                    <td className="px-3 py-1.5">{iss.message}</td>
                    <td className="num px-3 py-1.5 text-[var(--text-muted)]">{iss.row ?? "—"}</td>
                    <td className="max-w-[380px] truncate px-3 py-1.5 text-[var(--text-muted)]" title={iss.detail ?? ""}>{iss.detail ?? "—"}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        {quality.issues.length > shown.length && (
          <p className="border-t border-[var(--border)] px-4 py-2 text-[11px] text-[var(--text-muted)]">
            Showing {shown.length} of {quality.issues.length} issues. Narrow by severity or type to see the rest.
          </p>
        )}
      </Card>

      <p className="mt-3 text-[11px] text-[var(--text-muted)]">
        Generated from {meta.sourceFile} on {meta.generatedAt.slice(0, 10)} at {meta.generatedAt.slice(11, 19)} UTC.
      </p>
    </>
  );
}

function Stat({ label, value, sub, icon: Icon, color }: { label: string; value: string; sub: string; icon: React.ElementType; color: string }) {
  return (
    <Card className="print-avoid p-3.5">
      <div className="flex items-start justify-between">
        <span className="text-[10px] uppercase tracking-wide text-[var(--text-muted)]">{label}</span>
        <Icon size={14} style={{ color }} />
      </div>
      <div className="num mt-1.5 text-xl font-bold leading-none">{value}</div>
      <div className="mt-1 text-[10px] text-[var(--text-muted)]">{sub}</div>
    </Card>
  );
}